#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Movie Night Bot — Discord setup"

# ── Stage 1: prerequisites ────────────────────────────────────────────────
stage "Check prerequisites"
say "This bot uses Node's built-in node:sqlite module, which needs Node 22.5+."
if command -v node >/dev/null 2>&1; then
  NODE_VERSION=$(node -v)
  say "Found Node $NODE_VERSION."
  NODE_MAJOR=$(node -p "process.versions.node.split('.')[0]")
  NODE_MINOR=$(node -p "process.versions.node.split('.')[1]")
  if (( NODE_MAJOR < 22 || (NODE_MAJOR == 22 && NODE_MINOR < 5) )); then
    warn "Node $NODE_VERSION is too old — install Node 22.5 or newer before continuing."
  else
    say "Node version is OK."
  fi
else
  warn "Node not found on PATH — install Node 22.5+ before continuing."
fi
if [[ ! -d node_modules ]]; then
  step "Installing npm dependencies (npm install)..."
  npm install
else
  say "node_modules already present — skipping npm install."
fi
pause "Press Enter once Node is confirmed OK."

# ── Stage 2: create the Discord Application ───────────────────────────────
stage "Create the Discord Application"
say "Every bot lives inside a Discord 'Application'. We'll create one and grab its Client ID."
open_url "https://discord.com/developers/applications"
step "Click 'New Application' (top right)."
step "Give it a name, e.g. 'Movie Night Bot', accept the terms, click 'Create'."
step "You should land on the 'General Information' page — copy the 'Application ID' shown there."
ask DISCORD_CLIENT_ID "Paste the Application ID (Client ID):"
write_env DISCORD_CLIENT_ID "$DISCORD_CLIENT_ID"

# ── Stage 3: create the bot + get its token ────────────────────────────────
stage "Create the bot and copy its token"
say "Now we turn the application into a bot user and grab its login token."
step "In the left sidebar, click the 'Bot' tab."
step "Click 'Reset Token' (or 'Copy' if a token is already shown), confirm, then copy the token."
warn "This token is shown only once — copy it now. If you lose it, come back and Reset Token again."
step "Leave every 'Privileged Gateway Intent' toggle OFF — this bot doesn't need Message Content, Server Members, or Presence."
note "Nothing will appear on screen as you paste below — not even dots. That's intentional (it keeps the token out of your scrollback), it IS capturing what you type."
note "If right-click-paste seems to do nothing, try Ctrl+Shift+V or Shift+Insert instead — some terminals only support those while input is hidden."
note "Made a mistake? Press Ctrl+U to clear the whole hidden line and start over, then paste again and press Enter."
ask_secret DISCORD_TOKEN "Paste the bot token, then press Enter:"
while [[ -z "$DISCORD_TOKEN" ]]; do
  warn "Nothing was captured — if paste didn't work in this terminal, try Ctrl+Shift+V or Shift+Insert."
  ask_secret DISCORD_TOKEN "Paste the bot token, then press Enter:"
done
write_env DISCORD_TOKEN "$DISCORD_TOKEN"
note "Captured ${#DISCORD_TOKEN} character(s) for the token."

# ── Stage 4: invite the bot to your server ─────────────────────────────────
stage "Invite the bot to your server"
say "We'll build an invite URL with just the permissions this bot needs, then use it."
step "In the left sidebar, click 'OAuth2', then the 'URL Generator' tab."
step "Under 'Scopes', check: bot  and  applications.commands"
step "Under 'Bot Permissions' that appears, check: Send Messages, Embed Links (and 'Use Slash Commands' / 'Use Application Commands' if listed)."
step "Scroll down, copy the 'Generated URL'."
say "Paste that URL below and we'll open it — pick your server, review permissions, click Authorize."
note "The URL is long and will wrap across lines in your terminal — just paste it and press Enter."
note "Don't try to edit it with Backspace once it's wrapped (some terminals redraw wrapped lines oddly and can eat into the prompt text)."
note "If you need to redo it, press Ctrl+U first to reliably clear the whole line, then paste again."
ask INVITE_URL "URL:"
while [[ -z "$INVITE_URL" ]]; do
  warn "Nothing was captured — paste again (Ctrl+U first if the line looks off)."
  ask INVITE_URL "URL:"
done
open_url "$INVITE_URL"
confirm "Did you select your server and click Authorize?" || warn "Come back and finish the invite before running the bot."

# ── Stage 5: optional dev guild + finish .env ──────────────────────────────
stage "Optional: instant command registration for testing"
say "Slash commands registered globally can take up to an hour to show up."
say "For fast iteration, you can register them to just one server instead — they appear instantly there."
if confirm "Set a dev guild for instant registration? (recommended while testing)"; then
  say "Enable Developer Mode first: User Settings → Advanced → Developer Mode → On."
  step "Then right-click your server's icon in the sidebar → 'Copy Server ID'."
  ask DISCORD_DEV_GUILD_ID "Paste the Server (Guild) ID:"
  write_env DISCORD_DEV_GUILD_ID "$DISCORD_DEV_GUILD_ID"
else
  note "Skipping — commands will register globally (slower, but works everywhere the bot is invited)."
fi

# ── Stage 6: register the slash commands ───────────────────────────────────
stage "Register the /movienight slash command"
say "This runs 'npm run deploy-commands' using the values just saved to .env."
if confirm "Ready to register the command now?"; then
  npm run deploy-commands
else
  note "Skipped — run 'npm run deploy-commands' yourself whenever you're ready."
  SKIPPED+=("npm run deploy-commands (register the /movienight command)")
fi

# ── Stage 7: run the bot ───────────────────────────────────────────────────
stage "Run the bot"
say "Everything's configured. Start the bot with one of:"
step "npm run dev          — development, auto-restarts not included, just runs via ts-node"
step "npm run build && npm start   — compiled production run"
say "Once it logs 'Logged in as ...', try /movienight schedule in your server."
# ──────────────────────────────────────────────────────────────────────────

finish
